In [1]:
import numpy as np

In [6]:
arr1 = np.arange(10000000)

In [7]:
lst1 = list(range(10000000))

In [8]:
%time for _ in range(10): arr2 = arr1 * 2

Wall time: 211 ms


In [9]:
%time for _ in range(10): lst2 = [x*2 for x in lst1]

Wall time: 12.1 s


In [10]:
data = np.random.randn(3,4)

In [11]:
data

array([[ 0.8183041 , -1.18762912, -0.95066084,  0.16830915],
       [ 0.39593162, -0.02725542, -0.65991382, -1.97980922],
       [ 1.29713298,  1.52186552, -0.23300665, -0.37308   ]])

In [12]:
data + data

array([[ 1.63660821, -2.37525824, -1.90132168,  0.33661829],
       [ 0.79186323, -0.05451084, -1.31982764, -3.95961844],
       [ 2.59426595,  3.04373104, -0.4660133 , -0.74616001]])

In [13]:
data * 100

array([[  81.83041042, -118.76291198,  -95.06608411,   16.83091461],
       [  39.59316165,   -2.72554212,  -65.99138184, -197.98092181],
       [ 129.71329765,  152.18655193,  -23.30066507,  -37.30800049]])

In [14]:
data.shape

(3, 4)

In [15]:
data.dtype

dtype('float64')

In [20]:
numbers = [4,8.,15,16,23,42]

In [21]:
data2 = np.array(numbers)

In [22]:
data2

array([ 4.,  8., 15., 16., 23., 42.])

In [23]:
data2.dtype

dtype('float64')

In [24]:
data3 = np.array([[1,2,3,4],[5,6,7,8]])

In [25]:
data3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [27]:
data3.shape

(2, 4)

In [28]:
data2.ndim

1

In [29]:
data3.ndim

2

In [30]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
data4 = np.zeros((3,5,7))

In [33]:
data4.ndim

3

In [34]:
data4

array([[[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]]])

In [35]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [36]:
np.ones(20)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [39]:
data6 = np.array(['U20BA',2,3],dtype=np.unicode_)

In [40]:
data6.dtype

dtype('float64')

In [41]:
x = 3.14

In [42]:
x

3.14

In [43]:
y = int(x)

In [44]:
y

3

In [45]:
data8 = np.array([1.0,-2.7,3.2,4.5,5.6])

In [46]:
data8

array([ 1. , -2.7,  3.2,  4.5,  5.6])

In [47]:
data8.astype(np.int32)

array([ 1, -2,  3,  4,  5])

In [48]:
data9 = np.array(['1.25', '3.45', '7.376'], dtype=np.string_)

In [52]:
data10 = data9.astype(data8.dtype)

In [54]:
np.empty(8, dtype='u2')

array([ 8905, 42168, 53256, 55274, 47486, 49236, 22200, 29587],
      dtype=uint16)

In [53]:
data10.dtype

dtype('float64')

In [55]:
data42 = np.array([[1.,2,3],[4,5,6]])

In [56]:
data42

array([[1., 2., 3.],
       [4., 5., 6.]])

In [57]:
data42 * data42

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [58]:
data42 - data42

array([[0., 0., 0.],
       [0., 0., 0.]])

In [59]:
1 / data42

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [61]:
data42 ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [62]:
data43 = np.array([[3.,2,1],[6,5,4]])

In [64]:
data44 = data42 < data43

In [65]:
data44.dtype

dtype('bool')

In [66]:
arr1 = np.arange(10)

In [67]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
arr1[5]

5

In [69]:
arr1[5:8]

array([5, 6, 7])

In [70]:
arr1[5:8] = 42

In [71]:
arr1

array([ 0,  1,  2,  3,  4, 42, 42, 42,  8,  9])

In [80]:
arr2 = arr1[5:8].copy()

In [82]:
arr2

array([549, 549, 549])

In [83]:
arr2[1] = 108

In [84]:
arr2

array([549, 108, 549])

In [85]:
arr1

array([  0,   1,   2,   3,   4, 549, 549, 549,   8,   9])

In [77]:
arr2[:] = 549

In [78]:
arr2

array([549, 549, 549])

In [79]:
arr1

array([  0,   1,   2,   3,   4, 549, 549, 549,   8,   9])

In [86]:
# NVidia: cu(da)py

In [88]:
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [89]:
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [90]:
arr3[1]

array([4, 5, 6])

In [92]:
arr3[1][2]

6

In [93]:
arr3[1,2]

6

In [94]:
arr4 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [95]:
arr4.ndim

3

In [96]:
arr4

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [97]:
arr4.shape

(2, 2, 3)

In [99]:
arr4[1].copy()

(2, 3)

In [100]:
arr4[1][0][2]

9

In [101]:
arr4[1,0,2]

9

In [ ]:
arr4[1][:1][1:]

In [102]:
names = np.array(["jack", "james", "kate", "jin", "sun", "jack", "kate", "jack"])

In [103]:
numbers = np.random.randn(8,4)

In [104]:
numbers

array([[-0.33992864, -1.60245607,  2.64651662,  0.42558269],
       [-1.01867918,  0.15574845, -1.02013703, -0.76993352],
       [-0.35903408, -0.24042962, -0.04057032,  0.86572975],
       [ 1.38872146, -0.34716079,  0.35918238,  1.63992169],
       [ 0.78801839,  1.46294659,  0.31164386, -0.30118024],
       [ 0.20632875,  2.8619744 , -0.36783673,  0.0772469 ],
       [ 1.63172021,  0.15142088, -0.88615032, -1.84173001],
       [ 1.06689862, -0.63257032,  0.14224045, -0.56433612]])

In [105]:
names

array(['jack', 'james', 'kate', 'jin', 'sun', 'jack', 'kate', 'jack'],
      dtype='<U5')

In [106]:
names == 'jack'

array([ True, False, False, False, False,  True, False,  True])

In [109]:
numbers[~(names == 'jack'), 2:]

array([[-1.02013703, -0.76993352],
       [-0.04057032,  0.86572975],
       [ 0.35918238,  1.63992169],
       [ 0.31164386, -0.30118024],
       [-0.88615032, -1.84173001]])

In [110]:
mask1 = (names == 'jack') | (names=='kate')

In [112]:
numbers[mask1] = 0

In [113]:
numbers

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [-1.01867918,  0.15574845, -1.02013703, -0.76993352],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 1.38872146, -0.34716079,  0.35918238,  1.63992169],
       [ 0.78801839,  1.46294659,  0.31164386, -0.30118024],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [114]:
numbers2 = np.empty((8,4))

In [115]:
for i in range(8): numbers2[i] = i

In [116]:
numbers2

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [119]:
numbers2[[3,1,0,6]] # fancy indexing

array([[3., 3., 3., 3.],
       [1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [120]:
numbers2[[-3,-1,-2]]

array([[5., 5., 5., 5.],
       [7., 7., 7., 7.],
       [6., 6., 6., 6.]])

In [121]:
numbers3 = np.arange(32).reshape(8,4)

In [122]:
numbers3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [124]:
numbers4 = numbers3.reshape(2,16)

In [125]:
numbers4

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]])

In [126]:
numbers3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [127]:
numbers4[0,7] = 777

In [129]:
numbers3[1,3]

777

In [132]:
numbers5 = numbers3.reshape(2,2,2,4)

In [133]:
numbers5.ndim

4

In [134]:
numbers3.ndim

2

In [135]:
numbers3

array([[  0,   1,   2,   3],
       [  4,   5,   6, 777],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15],
       [ 16,  17,  18,  19],
       [ 20,  21,  22,  23],
       [ 24,  25,  26,  27],
       [ 28,  29,  30,  31]])

In [136]:
numbers3.T

array([[  0,   4,   8,  12,  16,  20,  24,  28],
       [  1,   5,   9,  13,  17,  21,  25,  29],
       [  2,   6,  10,  14,  18,  22,  26,  30],
       [  3, 777,  11,  15,  19,  23,  27,  31]])

In [137]:
nparr = np.arange(8)

In [138]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [139]:
np.sqrt(nparr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131])

In [140]:
np.exp(nparr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03])

In [145]:
nparr1 = np.random.randn(8)

In [146]:
nparr2 = np.random.randn(8)

In [147]:
nparr1

array([-1.1639434 ,  0.01484641, -0.3548825 , -0.87709889, -1.20163406,
       -0.91746815,  0.3508352 ,  0.86759644])

In [148]:
nparr2

array([ 0.86494332, -0.22553308,  0.43975059,  0.39607035,  2.61700424,
       -1.62380254, -0.43360169, -0.40234408])

In [149]:
np.maximum(nparr1,nparr2)

array([ 0.86494332,  0.01484641,  0.43975059,  0.39607035,  2.61700424,
       -0.91746815,  0.3508352 ,  0.86759644])

In [150]:
nparr1.mean()

-0.4102186193518728

In [151]:
nparr1.sum()

-3.2817489548149825

In [152]:
nparr1.min()

-1.2016340644145347

In [153]:
nparr1.max()

0.8675964407521398

In [154]:
nparr1.std()

0.7128705450193907

In [155]:
nparr1.var()

0.5081844139562433

In [156]:
nparr1

array([-1.1639434 ,  0.01484641, -0.3548825 , -0.87709889, -1.20163406,
       -0.91746815,  0.3508352 ,  0.86759644])

In [157]:
nparr1.sort()

In [158]:
nparr1

array([-1.20163406, -1.1639434 , -0.91746815, -0.87709889, -0.3548825 ,
        0.01484641,  0.3508352 ,  0.86759644])

In [159]:
names

array(['jack', 'james', 'kate', 'jin', 'sun', 'jack', 'kate', 'jack'],
      dtype='<U5')

In [160]:
np.unique(names)

array(['jack', 'james', 'jin', 'kate', 'sun'], dtype='<U5')

In [161]:
sorted(set(names))

['jack', 'james', 'jin', 'kate', 'sun']

In [163]:
np.savez('test.out', nparr1)

In [164]:
readarr = np.load('test.out.npz')

In [165]:
readarr